#!/usr/bin/env node

/**
 * Script to select the correct Prisma schema based on DATABASE_URL
 * - If DATABASE_URL starts with "file:", use SQLite schema
 * - Otherwise, use PostgreSQL schema
 */

const fs = require('fs');
const path = require('path');

// Load environment variables from .env file (if exists and accessible)
function loadEnv() {
  try {
    const envPath = path.join(__dirname, '..', '.env');
    if (fs.existsSync(envPath)) {
      const envContent = fs.readFileSync(envPath, 'utf8');
      envContent.split('\n').forEach(line => {
        const match = line.match(/^([^=:#]+)=(.*)$/);
        if (match) {
          const key = match[1].trim();
          const value = match[2].trim().replace(/^["']|["']$/g, '');
          if (!process.env[key]) {
            process.env[key] = value;
          }
        }
      });
    }
  } catch (error) {
    // .env file may not exist or be accessible, use environment variables directly
    // This is fine - environment variables can be set by the system
  }
}

loadEnv();

const databaseUrl = process.env.DATABASE_URL || '';
const isSQLite = databaseUrl.startsWith('file:');

const schemaDir = path.join(__dirname, '..', 'prisma');
const postgresqlSchema = path.join(schemaDir, 'schema.prisma');
const sqliteSchema = path.join(schemaDir, 'schema.sqlite.prisma');
const activeSchema = path.join(schemaDir, 'schema.active.prisma');

// Determine which schema to use
const sourceSchema = isSQLite ? sqliteSchema : postgresqlSchema;

if (!fs.existsSync(sourceSchema)) {
  console.error(`Error: Schema file not found: ${sourceSchema}`);
  process.exit(1);
}

// Copy the selected schema to schema.active.prisma
const schemaContent = fs.readFileSync(sourceSchema, 'utf8');
fs.writeFileSync(activeSchema, schemaContent);

// Update prisma.config.ts to use the active schema
const configPath = path.join(__dirname, '..', 'prisma.config.ts');
const configContent = `// This file was generated by select-schema.js
// DO NOT EDIT MANUALLY - This file is auto-generated
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.active.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
`;

fs.writeFileSync(configPath, configContent);

// After Prisma Client generation, create default.js files for proper module resolution
function createDefaultExports() {
  const prismaClientDirs = [
    path.join(__dirname, '..', 'node_modules', '@prisma', 'client', '.prisma', 'client'),
    path.join(__dirname, '..', 'node_modules', '.prisma', 'client'),
  ];

  prismaClientDirs.forEach(clientDir => {
    if (fs.existsSync(clientDir)) {
      const defaultJsPath = path.join(clientDir, 'default.js');
      const defaultDtsPath = path.join(clientDir, 'default.d.ts');
      const clientPath = path.join(clientDir, 'client');

      if (!fs.existsSync(defaultJsPath) && fs.existsSync(clientPath + '.ts')) {
        fs.writeFileSync(defaultJsPath, "module.exports = require('./client');\n");
        fs.writeFileSync(defaultDtsPath, "export * from './client';\n");
      }
    }
  });
}

// After Prisma Client generation, create default.js files for proper module resolution
function createDefaultExports() {
  const baseDir = path.join(__dirname, '..');
  const prismaClientDirs = [
    path.join(baseDir, 'node_modules', '@prisma', 'client', '.prisma', 'client'),
    path.join(baseDir, 'node_modules', '.pnpm', '@prisma+client@7.2.0_prisma@7.2.0_typescript@5.9.3', 'node_modules', '@prisma', 'client', '.prisma', 'client'),
  ];

  prismaClientDirs.forEach(clientDir => {
    if (fs.existsSync(clientDir)) {
      const defaultJsPath = path.join(clientDir, 'default.js');
      const defaultDtsPath = path.join(clientDir, 'default.d.ts');
      const clientTsPath = path.join(clientDir, 'client.ts');

      if (!fs.existsSync(defaultJsPath) && fs.existsSync(clientTsPath)) {
        fs.writeFileSync(defaultJsPath, "module.exports = require('./client');\n");
        fs.writeFileSync(defaultDtsPath, "export * from './client';\n");
        console.log(`✓ Created default exports in ${clientDir}`);
      }
    }
  });
}

console.log(`✓ Using ${isSQLite ? 'SQLite' : 'PostgreSQL'} schema (${sourceSchema})`);
console.log(`✓ DATABASE_URL: ${databaseUrl.substring(0, 50)}...`);

// Note: createDefaultExports() should be called after 'pnpm prisma generate'
// This is a helper function that can be called manually if needed
